### PR TITLE
[TECH SUPPORT] LPS-70627 Copy of a Journal Article keeps PublishDate empty

### PR DESCRIPTION
**Pull request by rimisaadouwork**
Hi,

Could you please review this commit.
https://issues.liferay.com/browse/LPS-70627

Thanks!

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Pull request submitted to https://github.com/liferay/com-liferay-journal/pull/186. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @rimisaadouwork,

For the next time, you should sent the pull request to the liferay users, because we execute some test validation only for that user.

I did it for you, please see: liferay#186

Thanks,
Eudaldo.

**Comment by rimisaadouwork** [comment]
Hi @ealonso ,

Could you please tell me more about this Liferay users. Because I am seeing this: liferay:master from ealonso:pr-9. So you are sending it to liferay/master?

Thanks!

**Comment by ealonso** [comment]
@rimisaadouwork 

Yes, I was referring to "liferay/master"

**Pull request closed without merging**
